name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: npm build
      run: npm run build --if-present
      env:
        CI: true
        REACT_APP_LOGO: ${{ secrets.REACT_APP_LOGO }}
        REACT_APP_FORM_CONTACT_ID: ${{ secrets.REACT_APP_FORM_CONTACT_ID }}
        REACT_APP_FORM_PRODUCTS_ID: ${{ secrets.REACT_APP_FORM_PRODUCTS_ID }}
        REACT_APP_FORM_ID: ${{ secrets.REACT_APP_FORM_ID }}
        REACT_APP_SPREADSHEET_ID: ${{ secrets.REACT_APP_SPREADSHEET_ID }}
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}